name: Fetch Kyodo

on:
  schedule:
    - cron: '0 */6 * * *'  # 6時間おきに実行
  workflow_dispatch:

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main  # mainブランチを使用

    - name: Fetch and Save RSS Files
      run: |
        mkdir -p xml_kyodo_$(date +\%Y\%m)
        urls=(
          "https://assets.wor.jp/rss/rdf/ynnews/news.rdf"
          "https://assets.wor.jp/rss/rdf/ynnews/national.rdf"
          "https://assets.wor.jp/rss/rdf/ynnews/politics.rdf"
          "https://assets.wor.jp/rss/rdf/ynnews/economics.rdf"
          "https://assets.wor.jp/rss/rdf/ynnews/world.rdf"
          "https://assets.wor.jp/rss/rdf/ynnews/sports.rdf"
          "https://assets.wor.jp/rss/rdf/ynnews/culture.rdf"
        )
        for url in "${urls[@]}"
        do
          suffix=$(basename $url | sed 's/\.rdf//')  # '.rdf' を取り除く
          if wget $url -O "xml_kyodo_$(date +\%Y\%m)/xml-kyodo_$(date +\%Y\%m%d%H%M)_$suffix.xml"; then
            echo "Downloaded $url"
          else
            echo "Failed to download $url"
            wget $url -O "xml_kyodo_$(date +\%Y\%m)/xml-kyodo_$(date +\%Y\%m%d%H%M)_$suffix.xml"  # エラー時に再試行
          fi
        done

    - name: Commit and Push files to main
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add xml_kyodo_$(date +\%Y\%m)/*
        git commit -m "Add RSS files for $(date +\%Y\%m%d%H%M)"
        git push origin main
