name: Fetch JIJI Sitemaps

on:
  schedule:
    - cron: '0 9 * * *'  # 毎日午後6時に実行（UTC 9時はJST 18時）
  workflow_dispatch:

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Node.js 20を使用するためv4を指定

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Fetch and Save XML Files
      run: |
        mkdir -p xml_jiji_$(date +\%Y\%m)
        urls=("https://www.jiji.com/sitemap/sitemap_jnb.xml"
              "https://www.jiji.com/sitemap/sitemap_akb.xml"
              "https://www.jiji.com/sitemap/sitemap_int.xml"
              "https://www.jiji.com/sitemap/sitemap_afp.xml"
              "https://www.jiji.com/sitemap/sitemap_newitem.xml"
              "https://www.jiji.com/sitemap/sitemap_myview.xml"
              "https://www.jiji.com/sitemap/sitemap_eco.xml"
              "https://www.jiji.com/sitemap/sitemap_jfn.xml"
              "https://www.jiji.com/sitemap/sitemap_soc.xml"
              "https://www.jiji.com/sitemap/sitemap_pol.xml"
              "https://www.jiji.com/sitemap/sitemap_obt.xml"
              "https://www.jiji.com/sitemap/sitemap_bsb.xml"
              "https://www.jiji.com/sitemap/sitemap_scr.xml"
              "https://www.jiji.com/sitemap/sitemap_spo.xml"
              "https://www.jiji.com/sitemap/sitemap_rgb.xml"
              "https://www.jiji.com/sitemap/sitemap_etm.xml"
              "https://www.jiji.com/sitemap/sitemap_ent.xml"
              "https://www.jiji.com/sitemap/sitemap_tha.xml"
              "https://www.jiji.com/sitemap/sitemap_prt.xml"
              "https://www.jiji.com/sitemap/sitemap_bw.xml"
              "https://www.jiji.com/sitemap/sitemap_bnw.xml"
              "https://www.jiji.com/sitemap/sitemap_cnp.xml"
              "https://www.jiji.com/sitemap/sitemap_prk.xml"
              "https://www.jiji.com/sitemap/sitemap_elc.xml"
              "https://www.jiji.com/sitemap/sitemap_use.xml"
              "https://www.jiji.com/sitemap/sitemap_ryl.xml"
              "https://www.jiji.com/sitemap/sitemap_olp.xml"
              "https://www.jiji.com/sitemap/sitemap_ert.xml"
              "https://www.jiji.com/sitemap/sitemap_ukr.xml"
              "https://www.jiji.com/sitemap/sitemap_smo.xml"
              "https://www.jiji.com/sitemap/sitemap_fsk.xml"
              "https://www.jiji.com/sitemap/sitemap_glf.xml"
              "https://www.jiji.com/sitemap/sitemap_bkb.xml"
              "https://www.jiji.com/sitemap/sitemap_tte.xml"
              "https://www.jiji.com/sitemap/sitemap_mng.xml"
              "https://www.jiji.com/sitemap/sitemap_dts.xml"
              "https://www.jiji.com/sitemap/sitemap_flash.xml"
              "https://www.jiji.com/sitemap/sitemap_ieq.xml"
              "https://www.jiji.com/sitemap/sitemap_photo_news.xml")
        for url in "${urls[@]}"
        do
          suffix=$(basename $url .xml)  # '.xml' 拡張子を取り除く
          if wget $url -O "xml_jiji_$(date +\%Y\%m)/xml-jiji_$(date +\%Y\%m%d)_$suffix.xml"; then
            echo "Downloaded $url"
          else
            echo "Failed to download $url"
            wget $url -O "xml_jiji_$(date +\%Y\%m)/xml-jiji_$(date +\%Y\%m%d)_$suffix.xml"  # エラー時にもう一度試行
          fi
        done

    - name: Commit and Push files to main
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add xml_jiji_$(date +\%Y\%m)/*
        git commit -m "Add XML files for $(date +\%Y\%m%d)"
        git push origin main
